# Generated by Django 5.0.4 on 2024-05-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-post'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
