# Generated by Django 5.0.4 on 2024-04-29 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_as', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('assessment', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Assessment')),
                ('feedback', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Feedback')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is feedback active')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedback',
                'ordering': ['created_as'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=120, verbose_name='Place')),
                ('full_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Full name')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comment')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'team',
                'ordering': ['place'],
            },
        ),
    ]
