# Generated by Django 5.0.4 on 2024-05-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='corporation',
            field=models.CharField(default='GOOGLE', max_length=60, verbose_name='Corporation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='full_name',
            field=models.CharField(default='ALEX JDF', max_length=60, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='place',
            field=models.CharField(default='TEAM LEED', max_length=60, verbose_name='Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/', verbose_name='Photo'),
        ),
    ]
